meta_product_name: "Bucket List with Kids"
meta_title: "Bucket List with Kids - Why wait until they've grown up?"
meta_description: "The best family-friendly bucket list travel activities from around the world"
meta_image: "cover.png"
twitter_account: "@bucketlistwithkids" # required for Twitter Cards
